source $VIMRUNTIME/defaults.vim

if !isdirectory($HOME . '/.vim')
    call mkdir($HOME . '/.vim')
endif

if !isdirectory($HOME . '/.vim/swap')
    call mkdir($HOME . '/.vim/swap')
endif

if !isdirectory($HOME . '/.vim/backup')
    call mkdir($HOME . '/.vim/backup')
endif

if !isdirectory($HOME . '/.vim/undo')
    call mkdir($HOME . '/.vim/undo')
endif

set viminfo+=n${HOME}/.vim/viminfo

set directory=${HOME}/.vim/swap//
set backupdir=${HOME}/.vim/backup//
set undodir=${HOME}/.vim/undo
set writebackup
set nobackup
set noswapfile
set noundofile
" doesn't seem to be a way to save orig files in backup dir...
" set patchmode=.orig


" let mapleader=","
" let maplocalleader=""

map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

nnoremap j gj
nnoremap k gk
nnoremap gj j
nnoremap gk k

vnoremap j gj
vnoremap k gk
vnoremap gj j
vnoremap gk k

set pastetoggle=<F10>


set hidden

" filetype plugin on
" filetype indent on

set showtabline=2
set laststatus=2

set list listchars=trail:#,tab:\|\ \ 

set ignorecase
set smartcase
set hlsearch
set incsearch
set magic

" keeps current color settings:
" syntax enable
" overrules current color settings with the defaults:
" syntax on

" set t_Co=256
set termguicolors
set noshowmode

" let g:two_firewatch_italics=1
colorscheme two-firewatch
let g:lightline= { 'colorscheme': 'powerline_two_firewatch', }

" set encoding=latin1
set fileformats=unix,dos

set report=0

set history=1000
set viminfo='100,/0,:0,<0,@0,s0,f1,h

set smarttab
set tabstop=4
set softtabstop=2
set shiftwidth=2
set expandtab
set autoindent
" set cindent

" set nowrap
set linebreak

set scrolloff=6
set sidescrolloff=16
set sidescroll=1

set showcmd
" set showmatch
" set matchtime=5

set number
set numberwidth=5
set relativenumber
set ruler

set modelines=0
set nomodeline

" if !filereadable($HOME . '/.vim/vimrc_extra')
" endif
